// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ST10252746_CLDV6212_POE_PART3.Data;

#nullable disable

namespace ST10252746_CLDV6212_POE_PART3.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20241106120832_FirstMigration(ApplicationDBContext,AppSettings,Program.cs)")]
    partial class FirstMigrationApplicationDBContextAppSettingsProgramcs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
